#!/usr/bin/env bash

image_name="awscli"

docker image build \
  --tag "$image_name" "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

docker container run \
  --tty \
  --rm \
  --volume ${PWD}:/cloudformation \
  --volume ${HOME}/.aws:/root/.aws:ro \
  "$image_name" \
  $@
