---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS IoT SQL Stack

Resources:
  IoTTopicRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-iot-topic-rule-role-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iot:Publish
                Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/iot/republished

  IotTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: sql_topic_rule
      TopicRulePayload:
        RuleDisabled: false
        Sql: |
          SELECT color AS rgb FROM 'iot/sql' WHERE temperature > 50
        Actions:
          - Republish:
              RoleArn: !GetAtt IoTTopicRuleRole.Arn
              Topic: iot/republished
