---
AWSTemplateFormatVersion: 2010-09-09
Description: Test

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        # not work
        #- Key: DomainSuffix
        #  Value: !Sub aws-${AWS::DomainSuffix}
        - Key: Partition
          Value: !Ref AWS::Partition # aws
