#!/usr/bin/env bash

image_name="awscli"

docker image build \
  --tag "$image_name" .

docker container run \
  --tty \
  --rm \
  --env AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id)" \
  --env AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key)" \
  "$image_name" \
  $@

docker container run \
  --tty \
  --rm \
  --env AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id)" \
  --env AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key)" \
  "$image_name" \
  cloudformation describe-stacks --stack-name ecs --query 'Stacks[].Outputs' --output table
