---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS IoT Multi Actions Stack

Parameters:
  IoTCertificateId:
    Type: String

Resources:
  IoTTing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: iot-multi-actions

  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: iot_multi_actions
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iot:*
            Resource:
              - "*"

  IoTPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:cert/${IoTCertificateId}

  IoTThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref IoTTing
      Principal: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:cert/${IoTCertificateId}

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: message
          AttributeType: S
      KeySchema:
        - AttributeName: message
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  IoTRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /iot/multi-actions/
      Policies:
        - PolicyName: multi-actions-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecordBatch
                Resource: !Sub arn:aws:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/${KinesisFirehose}
              - Effect: Allow
                Action: dynamodb:*
                Resource: !GetAtt DynamoDBTable.Arn

  KinesisFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  Bucket:
    Type: AWS::S3::Bucket

  KinesisFirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /${AWS::StackName}/kinesis-firehose

  KinesisFirehoseLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref KinesisFirehoseLogGroup
      LogStreamName: kinesis-firehose

  KinesisFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      S3DestinationConfiguration:
        RoleARN: !GetAtt KinesisFirehoseRole.Arn
        BucketARN: !GetAtt Bucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        CloudWatchLoggingOptions:
          Enabled: true
          LogStreamName: !Ref KinesisFirehoseLogStream
          LogGroupName: !Ref KinesisFirehoseLogGroup
        CompressionFormat: UNCOMPRESSED
        Prefix: iot-kinesis

  IotTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: iot_multi_actions
      TopicRulePayload:
        RuleDisabled: false
        Sql: SELECT * FROM 'iot/multi-actions'
        Actions:
          - Firehose:
              DeliveryStreamName: !Ref KinesisFirehose
              RoleArn: !GetAtt IoTRole.Arn
              Separator: "\n"
          - DynamoDBv2:
              RoleArn: !GetAtt IoTRole.Arn
              PutItem:
                TableName: !Ref DynamoDBTable
