---
Description: VPC Template

Parameters:
  NameTagPrefix:
    Type: String
    Default: test

Mappings:
  StackConfig:
    VPC:
      CIDR: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Fn::FindInMap:
          - StackConfig
          - VPC
          - CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${NameTagPrefix}-vpc
