#!/usr/bin/env bash

stream_name="$1"
image_name="data"
docker_file="Dockerfile.python"

docker image build \
  --file "$docker_file" \
  --tag "$image_name" .

docker container run \
  --tty \
  --rm \
  --env AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id)" \
  --env AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key)" \
  --env STREAM_NAME="$stream_name" \
  "$image_name"
