---
AWSTemplateFormatVersion: 2010-09-09
Description: VPC Template

Parameters:
  ArtifactBucket:
    Type: String
  NameTagPrefix:
    Type: String
    Default: test

Mappings:
  StackConfig:
    VPC:
      CIDR: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub s3://${ArtifactBucket}/vpc-param.yml
