AWSTemplateFormatVersion: "2010-09-09"
Description: Glue Stack

Resources:
  GlueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub glue-iam-role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  GlueTargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub glue-target-bucket-${AWS::StackName}

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub glue-database-${AWS::StackName}
        Description: !Sub |
          glue-database-${AWS::StackName}
        Parameters:
          key1: value1
          key2: value2

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub glue-crawler-${AWS::StackName}
      Description: !Sub |
        glue-crawler-${AWS::StackName}
      Role: !GetAtt GlueIAMRole.Arn
      Targets:
        S3Targets:
          - Path: !Ref GlueTargetBucket
      DatabaseName: !Ref GlueDatabase
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
        #DeleteBehavior: DELETE_FROM_DATABASE
        #DeleteBehavior: LOG
      TablePrefix: flights_
      #Schedule:
      #  ScheduleExpression: "cron(0/10 * ? * * *)"
