---
AWSTemplateFormatVersion: 2010-09-09
Description: Kinesis Firehose to S3 Stack

Parameters:
  SubscriptionFilterLogGroupName:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket

  KinesisFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - firehose.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  KinesisFirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /${AWS::StackName}/kinesis-firehose

  KinesisFirehoseLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref KinesisFirehoseLogGroup
      LogStreamName: kinesis-firehose

  KinesisFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      S3DestinationConfiguration:
        RoleARN: !GetAtt KinesisFirehoseRole.Arn
        BucketARN: !GetAtt Bucket.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
        CloudWatchLoggingOptions:
          Enabled: true
          LogStreamName: !Ref KinesisFirehoseLogStream
          LogGroupName: !Ref KinesisFirehoseLogGroup
        CompressionFormat: UNCOMPRESSED
        Prefix: !Sub ${AWS::StackName}/

  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - !Sub logs.${AWS::Region}.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess

  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt CloudWatchRole.Arn
      LogGroupName: !Ref SubscriptionFilterLogGroupName
      FilterPattern: |
        [version, account, eni, source!=192.168.*.*, destination, srcport, destport, protocol, packets, bytes, windowstart, windowend, action, flowlogstatus]
      DestinationArn: !Sub arn:aws:firehose:${AWS::Region}:${AWS::AccountId}:deliverystream/${KinesisFirehose}
