---
AWSTemplateFormatVersion: 2010-09-09
Description: OTA Update Stack

Parameters:
  IoTCertificateArn:
    Type: String

Resources:
  IoTThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: ota-update-thing

  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-iot-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iot:*
            Resource:
              - "*"

  IoTPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !Ref IoTCertificateArn

  IoTThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref IoTThing
      Principal: !Ref IoTCertificateArn

  FirmwareBucket:
    Type: AWS::S3::Bucket

  IoTJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-iot-job-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub ${FirmwareBucket.Arn}/*

Outputs:
  IoTThingName:
    Value: !Ref IoTThing
  FirmwareBucketName:
    Value: !Ref FirmwareBucket
